=== regisg495/Sax-Jax-Dom-Parser/src/com/transporte/carga/static/resources/xml/carga.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.w3schools.com"
           xmlns="http://www.w3schools.com"
           elementFormDefault="qualified"
>

    <xs:simpleType name="nonEmptyString">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="capitalizedNonEmptyStringWithNumber">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z]*(\s[A-Za-z0-9]*)*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="capitalizedNonEmptyString">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z][a-z]*(\s[A-Z][a-z]*)*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="lowerNonEmptyString">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zà-ú0-9]*(\s[a-zà-ú0-9]*)*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipo">
        <xs:restriction base="xs:string">
            <xs:enumeration value="caixa"/>
            <xs:enumeration value="barril"/>
            <xs:enumeration value="saco"/>
            <xs:enumeration value="caixa refrigerada"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="unidade">
        <xs:restriction base="xs:string">
            <xs:enumeration value="peça"/>
            <xs:enumeration value="kilo"/>
            <xs:enumeration value="litro"/>
            <xs:enumeration value="unidade"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="quantidade">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:double">
                    <xs:attribute name="unidade" type="unidade" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="abstractContainer" abstract="true">
        <xs:sequence>
            <xs:element name="responsavel" type="capitalizedNonEmptyStringWithNumber"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
        <xs:attribute name="tipo" type="tipo" use="required"/>
    </xs:complexType>

    <xs:group name="containerContentGroup">
        <xs:sequence>
            <xs:element name="produto" type="lowerNonEmptyString"/>
            <xs:element ref="quantidade"/>
            <xs:element name="valor" type="xs:double"/>
        </xs:sequence>
    </xs:group>

    <xs:complexType name="container">
        <xs:complexContent>
            <xs:extension base="abstractContainer">
                <xs:sequence>
                    <xs:element name="destino" type="xs:string"/>
                    <xs:choice maxOccurs="unbounded">
                        <xs:group ref="containerContentGroup"/>
                        <xs:element name="container" type="subcontainer" maxOccurs="unbounded"/>
                    </xs:choice>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="subcontainer">
        <xs:complexContent>
            <xs:extension base="abstractContainer">
                <xs:sequence>
                    <xs:choice>
                        <xs:group ref="containerContentGroup"/>
                        <xs:element name="container" type="subcontainer" maxOccurs="unbounded"/>
                    </xs:choice>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="carga">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="responsavel" type="capitalizedNonEmptyStringWithNumber"/>
                <xs:element name="origem" type="capitalizedNonEmptyString"/>
                <xs:element maxOccurs="unbounded" name="container" type="container"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== regisg495/Sax-Jax-Dom-Parser/src/com/transporte/carga/static/resources/xml/carga.xml
<?xml version="1.0" encoding="UTF-8"?>
<carga xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://www.w3schools.com"
       xsi:schemaLocation="http://www.w3schools.com carga.xsd">
    <responsavel>Empresa 1 SA</responsavel>
    <origem>Rio Grande</origem>
    <container tipo="caixa" id="1">
        <responsavel>Empresa 2 SA</responsavel>
        <destino>São Paulo</destino>
        <container tipo="caixa" id="2">
            <responsavel>Empresa 3 SA</responsavel>
            <produto>sabonete em barra</produto>
            <quantidade unidade="unidade">30</quantidade>
            <valor>55.99</valor>
        </container>
        <container tipo="caixa" id="3">
            <responsavel>Empresa 4 SA</responsavel>
            <container tipo="caixa" id="4">
                <responsavel>Empresa 4 SA</responsavel>
                <produto>terra humus</produto>
                <quantidade unidade="kilo">37.5</quantidade>
                <valor>96.58</valor>
            </container>
            <container tipo="saco" id="5">
                <responsavel>Empresa 4 SA</responsavel>
                <produto>uréia</produto>
                <quantidade unidade="kilo">40.2</quantidade>
                <valor>113.82</valor>
            </container>
        </container>
    </container>
    <container tipo="barril" id="6">
        <responsavel>Empresa 2 SA</responsavel>
        <destino>Porto Alegre</destino>
        <produto>vinagre de vinho tinto</produto>
        <quantidade unidade="litro">200</quantidade>
        <valor>546.66</valor>
    </container>
    <container tipo="caixa refrigerada" id="7">
        <responsavel>Empresa 2 SA</responsavel>
        <destino>Porto Alegre</destino>
        <container tipo="saco" id="8">
            <responsavel>Empresa 4 SA</responsavel>
            <produto>carne moída de 2a</produto>
            <quantidade unidade="kilo">23.6</quantidade>
            <valor>258.41</valor>
        </container>
        <container tipo="caixa" id="9">
            <responsavel>Empresa 5 SA</responsavel>
            <produto>1kg de queijo prato</produto>
            <quantidade unidade="peça">12</quantidade>
            <valor>96.58</valor>
        </container>
    </container>
        <container id="10" tipo="caixa">
            <responsavel>Empresa 4 SA</responsavel>
            <destino>São Paulo</destino>
            <container id="12" tipo="caixa">
                <responsavel>Empresa 2 SA</responsavel>
                <container id="13" tipo="caixa">
                    <responsavel>Empresa 5 SA</responsavel>
                    <container id="14" tipo="caixa refrigerada">
                        <responsavel>Empresa 1 SA</responsavel>
                        <produto>cerveja skol litro</produto>
                        <quantidade unidade="litro">400</quantidade>
                        <valor>1500.23</valor>
                    </container>
                    <container id="15" tipo="caixa refrigerada">
                        <responsavel>Empresa 1 SA</responsavel>
                        <produto>cerveja brahma latão</produto>
                        <quantidade unidade="unidade">600</quantidade>
                        <valor>1000.23</valor>
                    </container>
                    <container id="16" tipo="caixa refrigerada">
                        <responsavel>Empresa 1 SA</responsavel>
                        <produto>cerveja budweiser latão</produto>
                        <quantidade unidade="unidade">400</quantidade>
                        <valor>400.70</valor>
                    </container>
                </container>
                <container id="17" tipo="caixa">
                    <responsavel>Empresa 3 SA</responsavel>
                    <container id="18" tipo="caixa">
                        <responsavel>Empresa 6 SA</responsavel>
                        <produto>ritalina 10mg</produto>
                        <quantidade unidade="unidade">500</quantidade>
                        <valor>3021.12</valor>
                    </container>
                    <container id="19" tipo="caixa">
                        <responsavel>Empresa 6 SA</responsavel>
                        <produto>omeprazol 20mg</produto>
                        <quantidade unidade="unidade">200</quantidade>
                        <valor>400.12</valor>
                    </container>
                    <container id="20" tipo="caixa">
                        <responsavel>Empresa 6 SA</responsavel>
                        <produto>diazepam 5mg</produto>
                        <quantidade unidade="unidade">500</quantidade>
                        <valor>621.21</valor>
                    </container>
                </container>
            </container>
            <container id="21" tipo="saco">
                <responsavel>Empresa 3 SA</responsavel>
                <produto>farinha de trigo</produto>
                <quantidade unidade="unidade">400</quantidade>
                <valor>320.11</valor>
            </container>
            <container id="22" tipo="saco">
                <responsavel>Empresa 3 SA</responsavel>
                <produto>farinha de mandioca</produto>
                <quantidade unidade="unidade">200</quantidade>
                <valor>156.12</valor>
            </container>
        </container>
</carga>
